version: "3.9"

services:
  database:
    container_name: postgres_db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  back:
    container_name: backend
    build: ./back
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    volumes:
      - ./back:/server
      - back_node_modules:/server/node_modules

volumes:
  back_node_modules:
